### ISSUE TITLE
Opening console does nothing.

### ISSUE THREAD

**Issue by tideonsky** [philhk/discord-name-sniper#4]
I opened it once, told me to change config. I changed config. Adding both a name to the namelist and my token makes it close itself without telling me anything, not even with webhook. Here is a picture of my config:
![image](https://github.com/philhk/discord-name-sniper/assets/135397642/20aacefb-eecc-4f58-89b5-2370f6c2878a)

**Comment by philhk** [comment]
Your format is wrong. An example with your current configuration might look like this.

```
{
    "namelists": {
        "coolnames": ["tide"]
    },
    "accounts": [{ "token": "<token>", "namelists": ["coolnames"] }],
    "delays": {
        "nameRetry": 400,
        "retry": 3800
    },
    "webhook": {
        "enabled": true,
        "sendFailures": true,
        "pingRoleId": "1042326274548432906",
        "url": "<webhook>"
    }
}
```

**Comment by tideonsky** [comment]
Do I need to have two tokens? I've only got one that I'm using at the moment

**Comment by tideonsky** [comment]
Oh nevermind, it works. Thank you for the help.
